import { START, END, StateGraph, Annotation } from "@langchain/langgraph";
import { HumanMessage } from "@langchain/core/messages";
import { mistralAIModel, cohereModel } from "./model.ai.js";

type Judge = {
  solution_1_score: number;
  solution_2_score: number;
  solution_1_reasoning: string;
  solution_2_reasoning: string;
};

type GraphStateType = {
  problem: string;
  solution_1: string;
  solution_2: string;
  judge: Judge;
};

const GraphState = Annotation.Root({
  problem: Annotation<string>(),
  solution_1: Annotation<string>(),
  solution_2: Annotation<string>(),
  judge: Annotation<Judge>(),
});

function getText(response: any): string {
  if (typeof response.content === "string") return response.content;

  if (Array.isArray(response.content)) {
    return response.content.map((item: any) => item.text || "").join("\n");
  }

  return "";
}

const solutionNode = async (state: GraphStateType) => {
  const [mistralResponse, cohereResponse] = await Promise.all([
    mistralAIModel.invoke(state.problem),
    cohereModel.invoke(state.problem),
  ]);

  return {
    solution_1: getText(mistralResponse),
    solution_2: getText(cohereResponse),
  };
};

const judgeNode = async (state: GraphStateType) => {
  const prompt = `
You are a strict coding judge.

Problem:
${state.problem}

Solution 1:
${state.solution_1}

Solution 2:
${state.solution_2}

Return only valid JSON:
{
  "solution_1_score": 0,
  "solution_2_score": 0,
  "solution_1_reasoning": "",
  "solution_2_reasoning": ""
}
`;

  const response = await cohereModel.invoke([
    new HumanMessage(prompt),
  ]);

  const text = getText(response)
    .replace(/```json/g, "")
    .replace(/```/g, "")
    .trim();

  const jsonStart = text.indexOf("{");
const jsonEnd = text.lastIndexOf("}");

if (jsonStart === -1 || jsonEnd === -1) {
  throw new Error("Judge response is not valid JSON");
}

const parsedJudge = JSON.parse(text.slice(jsonStart, jsonEnd + 1)) as Judge;

return {
  judge: parsedJudge,
};
};

const graph = new StateGraph(GraphState)
  .addNode("solution", solutionNode)
  .addNode("judge_node", judgeNode)
  .addEdge(START, "solution")
  .addEdge("solution", "judge_node")
  .addEdge("judge_node", END)
  .compile();

export default async function runGraph(problem: string) {
  return await graph.invoke({
    problem,
    solution_1: "",
    solution_2: "",
    judge: {
      solution_1_score: 0,
      solution_2_score: 0,
      solution_1_reasoning: "",
      solution_2_reasoning: "",
    },
  });
}



















// import { START, END, StateGraph, StateSchema, type GraphNode } from '@langchain/langgraph'
// import z from 'zod'
// import { mistralAIModel, cohereModel, geminiModel } from './model.ai.js'
// import { createAgent, HumanMessage, providerStrategy, toolStrategy } from 'langchain'


// const state = new StateSchema({
//     problem: z.string().default(""),
//     solution_1: z.string().default(""),
//     solution_2: z.string().default(""),
//     judge: z.object({
//         solution_1_score: z.number().default(0),
//         solution_2_score: z.number().default(0),
//         solution_1_reasoning: z.string().default(""),
//         solution_2_reasoning: z.string().default(""),
//     })
// })


// const solutionNode: GraphNode<typeof state> = async (state) => {

//     const [mistralResponse, cohereResponse] = await Promise.all([
//         mistralAIModel.invoke(state.problem),
//         cohereModel.invoke(state.problem)
//     ])

//     return {
//         solution_1: mistralResponse.text,
//         solution_2: cohereResponse.text,
//     }
// }

// const judgeNode: GraphNode<typeof state> = async (state) => {

//     const { problem, solution_1, solution_2 } = state

//     const judge = createAgent({
//         model: geminiModel,
//         responseFormat:providerStrategy(z.object({
//             solution_1_score: z.number().min(0).max(10),
//             solution_2_score: z.number().min(0).max(10),
//             solution_1_reasoning: z.string(),
//             solution_2_reasoning: z.string(),
//         })),
//         systemPrompt: `You are a judge tasked with evaluating two solutions
//         generated by diffreent AI models. Please provide a score out of 10 for each 
//         solution, along with your reasoning for the scores.`
//     })

//     const judgeResponse = await judge.invoke({
//         messages: [
//             new HumanMessage(`
//                 Problem: ${problem}
//                 Solution 1: ${solution_1}
//                 Solution_2: ${solution_2}
//                 Please evaluate the solution and provide scores and reasoning.
//                 `)
//         ]
//     })

//     const {
//         solution_1_score,
//         solution_2_score,
//         solution_1_reasoning,
//         solution_2_reasoning
//     } = judgeResponse.structuredResponse

//     return {
//         judge:{
//             solution_1_score,
//             solution_2_score,
//             solution_1_reasoning,
//             solution_2_reasoning
//         }
//     }

// }

// const graph = new StateGraph(state)
//     .addNode("solution", solutionNode)
//     .addNode("judge_node", judgeNode)
//     .addEdge(START, "solution")
//     .addEdge("solution", "judge_node")
//     .addEdge("judge_node", END)
//     .compile()

// export default async function runGraph(problem:string) {
    
//     const result = await graph.invoke({
//         problem: problem
//     })

//     return result
// }


